### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by Dani20000** [Dark-Arcana/antimatter-chemistry#199] opened 2019-10-12 12:47 UTC
I'm playing the new (1.2.25) Antimatter Chemistry version and the game immediatially crashes. The game doesn't create any crash log, only normal log:
[latest.log](https://github.com/al132mc/antimatter-chemistry/files/3720668/latest.log)

**Comment by al132mc** [comment] 2019-10-12 15:01
Someone else is getting a similar crash on one of my other packs.. I have absolutely no idea what could be causing this.

**Comment by vertex101** [comment] 2019-10-12 21:19
from what i have read about the errors that is thrown is there is a dupe mod that is causing it so u might need to check your mods folder to make sure there isnt a dupe of any mod @Dani20000

**Comment by Dani20000** [comment] 2019-10-22 17:35
I deleted and reinstalled the pack for the third time and now works fine (always 1.2.25 version)...

**Comment by Karpathis** [comment] 2019-11-24 01:06
> I deleted and reinstalled the pack for the third time and now works fine (always 1.2.25 version)...



> from what I have read about the errors that are thrown in there is a dupe mod that is causing it so u might need to check your mods folder to make sure there isn't a dupe of any mod @Dani20000

I've had a similar issue with 1.2.26, I've looked through the folders and I couldn't find any mods that repeated.

**Closed** 2022-05-02 14:17 UTC
Labels: Crash Bug, outdated
